[package]
name = "network"
version = "0.1.0"
authors = ["Kaiyuan Xu <xuky@shanghaitech.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.12.1"
